### PR TITLE
Improve bridges

### PR DESCRIPTION
**Pull request by rojserbest**

### CODE REVIEW

**Comment by MarshalX** [comment]
Don't confuse these two variables. **They are of different types**. One constant to connect, the other can be updated (in update handler). There is 2 types: InputGroupCall and GroupCall

**Comment by MarshalX** [comment]
If you want to use only self.group_call you need to convert it sometime to InputGroupCall

**Comment by rojserbest** [comment]
image
`self.full_chat.call` is the same as `self.group_call`, isn't it?

**Comment by MarshalX** [comment]
But its not needed because we can use static value of full_chat.call. Call id can be changes only by recteating of group call. So there is no need to handle updated group calls from UpdateGroupCall update. Its necessary to handle changing settings of group call. For example "new members are muted"

> If you want to use only self.group_call you need to convert it sometime to InputGroupCall before using in requests

**Comment by MarshalX** [comment]
> image
> `self.full_chat.call` is the same as `self.group_call`, isn't it?

This is true until the first update is received. It is temporarily used as a value of self.group_call to be able to compare the call by ID while processing updates. To know should we handle this update or not

**Comment by rojserbest** [comment]
So why do you use it in check call if it is something temporary and not to be used?

**Comment by MarshalX** [comment]
> So why do you use it in check call if it is something temporary and not to be used?

image

**Comment by MarshalX** [comment]
> So why do you use it in check call if it is something temporary and not to be used?

temp is value. same as self.full_chat.call. Var is not a temp

**Comment by rojserbest** [comment]
OK. What about why you don't check if self.group_call is not None in edit participant?

**Comment by MarshalX** [comment]
> OK. What about why you don't check if self.group_call is not None in edit participant?

Because editing a participant cannot be called without joining to a call. Developers should check if the bot is on the call or not.

In turn, checking whether we are in a voice chat **should always work and return a boolean**. Ofc it can be called before the start of the call. For example before editing of participant)

**Comment by rojserbest** [comment]
Alright, thanks for your information. Closing this.

**Pull request closed without merging**
