### PR TITLE
typo.

### PR DESCRIPTION
**Pull request by xditya**

### CODE REVIEW

**Comment by MarshalX** [comment]
In this case, you need to change the double quotes to single quotes.

**Comment by rojvv** [comment]
Mh, and:
- Why would one need a dot in...
  - exception message?
  - commit message?

The commit message might be changed.

**Comment by MarshalX** [comment]
@rojserbest Exception

**Comment by rojvv** [comment]
@MarshalX yes, it's not popular to have a full stop in the end of its first param.

**Comment by xditya** [comment]
> Mh, and:
> 
> * Why would one need a dot in...
>   
>   * exception message?
>   * commit message?
> 
> The commit message might be changed.

That's basic punctuation. You should not have skipped your English classes, maybe :)

**Comment by MarshalX** [comment]
> In this case, you need to change the double quotes to single quotes.

@xditya

**Comment by rojvv** [comment]
> > Mh, and:
> > 
> > * Why would one need a dot in...
> >   
> >   * exception message?
> >   * commit message?
> > 
> > The commit message might be changed.
> 
> That's basic punctuation. You should not have skipped your English classes, maybe :)

That's basic Python standards. You shouldn't have skipped your Python classes too. :P

**Comment by rojvv** [comment]
image
You looked too serious about periods, here you missed one here.

**Comment by xditya** [comment]
> > In this case, you need to change the double quotes to single quotes.
> 
> @xditya 

Oh, okay

**Comment by xditya** [comment]
I don't mean to offend anyone by opening a pr. If contributing stuff triggers the other "contributors", I shall not do so anymore. Thanks.

**Pull request closed without merging**
