### PR TITLE
fix broken command in the build instructions

### PR DESCRIPTION
**Pull request by rojvv**

### CODE REVIEW

**Comment by MarshalX** [comment]
It's not broken. I prefer use git over ssh instead of https...

**Comment by rojvv** [comment]
It's not working on Linux.

**Comment by rojvv** [comment]
```zsh
[] ~ git clone git@github.com:MarshalX/tgcalls.git --recursive
Cloning into 'tgcalls'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[] ~ 
```

**Comment by MarshalX** [comment]
It's ssh... you need to have default key in your machine

**Comment by rojvv** [comment]
Ah.

**Comment by rojvv** [comment]
Dobriy dyen.

**Comment by rojvv** [comment]
Wait, if I was you I'd still put a more accessible way

**Comment by rojvv** [comment]
I don't know if you change your mind, but I'll let the closing decision for you to make

**Pull request closed without merging**
