### PR TITLE
Use groupcall_default_join_as

### PR DESCRIPTION
**Pull request by rojserbest**

### CODE REVIEW

**Comment by MarshalX** [comment]
PR to main. Reject

**Comment by rojserbest** [comment]
> PR to main. Reject

To where?

**Comment by rojserbest** [comment]
image

**Comment by MarshalX** [comment]
Dev

**Comment by rojserbest** [comment]
Wasn't that 'to main'?

**Comment by rojserbest** [comment]
> Dev

ok lol why do you close it, you can change it with a button

**Comment by rojserbest** [comment]
please reopen @MarshalX

**Pull request closed without merging**
